package com.bannink.joys;

import com.bannink.joys.domain.*;
import com.bannink.joys.repository.IChallengeRepository;
import com.bannink.joys.repository.IGameRepository;
import com.bannink.joys.repository.IUserRepository;
import com.bannink.joys.repository.RoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;


@Component
public class DataLoader implements ApplicationRunner {
    private IGameRepository gameInformationRepository;
    private IChallengeRepository challengeInformationRepository;
    private PasswordEncoder encoder;
    private RoleRepository roleRepository;
    private IUserRepository userRepository;

    @Autowired
    public DataLoader(IGameRepository gameInformationRepository, IChallengeRepository challengeInformationRepository, PasswordEncoder encoder, RoleRepository roleRepository, IUserRepository userRepository) {
        this.gameInformationRepository = gameInformationRepository;
        this.challengeInformationRepository = challengeInformationRepository;
        this.encoder = encoder;
        this.roleRepository = roleRepository;
        this.userRepository = userRepository;
    }
    public void run(ApplicationArguments args) {
        Game game = new Game();
        game.setName("5 Minute Challenge");
        game.setDescription("Earn 10 XP! Take a quick break to place your attention back to yourself with short challenge");
        gameInformationRepository.save(game);
        Game game2 = new Game();
        game2.setName("15 Minute Challenge");
        game2.setDescription("Earn 20 XP! This is a great way to practice mindfullness daily and it will only take 15 minutes out of your day");
        gameInformationRepository.save(game2);
        Game game3 = new Game();
        game3.setName("24 Hour Challenge");
        game3.setDescription("Earn 100 XP! Think you're up for a difficult challenge? You will get a challenge that you have to practice throughout the day");
        gameInformationRepository.save(game3);

        Challenge challenge1 = new Challenge();
        challenge1.setName("Challenge1");
        challenge1.setLevel("5 minute challenge");
        challenge1.setDescription("descr");
        challenge1.setValue(10);
        challengeInformationRepository.save(challenge1);
        Challenge challenge2 = new Challenge();
        challenge2.setName("Challenge2");
        challenge2.setLevel("5 minute challenge");
        challenge2.setDescription("descr");
        challenge2.setValue(10);
        challengeInformationRepository.save(challenge2);
        Challenge challenge3 = new Challenge();
        challenge3.setName("Challenge3");
        challenge3.setLevel("5 minute challenge");
        challenge3.setDescription("descr");
        challenge3.setValue(10);
        challengeInformationRepository.save(challenge3);
        Challenge challenge4 = new Challenge();
        challenge4.setName("Challenge4");
        challenge4.setLevel("5 minute challenge");
        challenge4.setDescription("descr");
        challenge4.setValue(10);
        challengeInformationRepository.save(challenge4);
        Challenge challenge5 = new Challenge();
        challenge5.setName("Challenge5");
        challenge5.setLevel("5 minute challenge");
        challenge5.setDescription("descr");
        challenge5.setValue(10);
        challengeInformationRepository.save(challenge5);
        Challenge challenge6 = new Challenge();
        challenge6.setName("Challenge6");
        challenge6.setLevel("5 minute challenge");
        challenge6.setDescription("descr");
        challenge6.setValue(10);
        challengeInformationRepository.save(challenge6);
        Challenge challenge7 = new Challenge();
        challenge7.setName("Challenge7");
        challenge7.setLevel("5 minute challenge");
        challenge7.setDescription("descr");
        challenge7.setValue(10);
        challengeInformationRepository.save(challenge7);
        Challenge challenge8 = new Challenge();
        challenge8.setName("Challenge8");
        challenge8.setLevel("5 minute challenge");
        challenge8.setDescription("descr");
        challenge8.setValue(10);
        challengeInformationRepository.save(challenge8);
        Challenge challenge9 = new Challenge();
        challenge9.setName("Challenge9");
        challenge9.setLevel("5 minute challenge");
        challenge9.setDescription("descr");
        challenge9.setValue(10);
        challengeInformationRepository.save(challenge9);
        Challenge challenge10 = new Challenge();
        challenge10.setName("Challenge10");
        challenge10.setLevel("5 minute challenge");
        challenge10.setDescription("descr");
        challenge10.setValue(10);
        challengeInformationRepository.save(challenge10);

        Challenge challenge11 = new Challenge();
        challenge11.setName("Challenge11");
        challenge11.setLevel("15 minute challenge");
        challenge11.setDescription("descr");
        challenge11.setValue(20);
        challengeInformationRepository.save(challenge11);
        Challenge challenge12 = new Challenge();
        challenge12.setName("Challenge12");
        challenge12.setLevel("15 minute challenge");
        challenge12.setDescription("descr");
        challenge12.setValue(20);
        challengeInformationRepository.save(challenge12);
        Challenge challenge13 = new Challenge();
        challenge13.setName("Challenge13");
        challenge13.setLevel("15 minute challenge");
        challenge13.setDescription("descr");
        challenge13.setValue(20);
        challengeInformationRepository.save(challenge13);
        Challenge challenge14 = new Challenge();
        challenge14.setName("Challenge14");
        challenge14.setLevel("15 minute challenge");
        challenge14.setDescription("descr");
        challenge14.setValue(20);
        challengeInformationRepository.save(challenge14);
        Challenge challenge15 = new Challenge();
        challenge15.setName("Challenge15");
        challenge15.setLevel("15 minute challenge");
        challenge15.setDescription("descr");
        challenge15.setValue(20);
        challengeInformationRepository.save(challenge15);
        Challenge challenge16 = new Challenge();
        challenge16.setName("Challenge16");
        challenge16.setLevel("15 minute challenge");
        challenge16.setDescription("descr");
        challenge16.setValue(20);
        challengeInformationRepository.save(challenge16);
        Challenge challenge17 = new Challenge();
        challenge17.setName("Challenge17");
        challenge17.setLevel("15 minute challenge");
        challenge17.setDescription("descr");
        challenge17.setValue(20);
        challengeInformationRepository.save(challenge17);
        Challenge challenge18 = new Challenge();
        challenge18.setName("Challenge18");
        challenge18.setLevel("15 minute challenge");
        challenge18.setDescription("descr");
        challenge18.setValue(20);
        challengeInformationRepository.save(challenge18);
        Challenge challenge19 = new Challenge();
        challenge19.setName("Challenge19");
        challenge19.setLevel("15 minute challenge");
        challenge19.setDescription("descr");
        challenge19.setValue(20);
        challengeInformationRepository.save(challenge19);
        Challenge challenge20 = new Challenge();
        challenge20.setName("Challenge20");
        challenge20.setLevel("15 minute challenge");
        challenge20.setDescription("descr");
        challenge20.setValue(20);
        challengeInformationRepository.save(challenge20);

        Challenge challenge21 = new Challenge();
        challenge21.setName("Challenge21");
        challenge21.setLevel("24 hour challenge");
        challenge21.setDescription("descr");
        challenge21.setValue(100);
        challengeInformationRepository.save(challenge21);
        Challenge challenge22 = new Challenge();
        challenge22.setName("Challenge22");
        challenge22.setLevel("24 hour challenge");
        challenge22.setDescription("descr");
        challenge22.setValue(100);
        challengeInformationRepository.save(challenge22);
        Challenge challenge23 = new Challenge();
        challenge23.setName("Challenge23");
        challenge23.setLevel("24 hour challenge");
        challenge23.setDescription("descr");
        challenge23.setValue(100);
        challengeInformationRepository.save(challenge23);
        Challenge challenge24 = new Challenge();
        challenge24.setName("Challenge24");
        challenge24.setLevel("24 hour challenge");
        challenge24.setDescription("descr");
        challenge24.setValue(100);
        challengeInformationRepository.save(challenge24);
        Challenge challenge25 = new Challenge();
        challenge25.setName("Challenge25");
        challenge25.setLevel("24 hour challenge");
        challenge25.setDescription("descr");
        challenge25.setValue(100);
        challengeInformationRepository.save(challenge25);
        Challenge challenge26 = new Challenge();
        challenge26.setName("Challenge26");
        challenge26.setLevel("24 hour challenge");
        challenge26.setDescription("descr");
        challenge26.setValue(100);
        challengeInformationRepository.save(challenge26);
        Challenge challenge27 = new Challenge();
        challenge27.setName("Challenge27");
        challenge27.setLevel("24 hour challenge");
        challenge27.setDescription("descr");
        challenge27.setValue(100);
        challengeInformationRepository.save(challenge27);
        Challenge challenge28 = new Challenge();
        challenge28.setName("Challenge28");
        challenge28.setLevel("24 hour challenge");
        challenge28.setDescription("descr");
        challenge28.setValue(100);
        challengeInformationRepository.save(challenge28);
        Challenge challenge29 = new Challenge();
        challenge29.setName("Challenge29");
        challenge29.setLevel("24 hour challenge");
        challenge29.setDescription("descr");
        challenge29.setValue(100);
        challengeInformationRepository.save(challenge29);
        Challenge challenge30 = new Challenge();
        challenge30.setName("Challenge30");
        challenge30.setLevel("24 hour challenge");
        challenge30.setDescription("descr");
        challenge30.setValue(100);
        challengeInformationRepository.save(challenge30);

        List<Challenge> challenges = new ArrayList<>();
        challenges.add(challenge1);
        challenges.add(challenge2);
        challenges.add(challenge3);
        challenges.add(challenge4);
        challenges.add(challenge5);
        challenges.add(challenge6);
        challenges.add(challenge7);
        challenges.add(challenge8);
        challenges.add(challenge9);
        challenges.add(challenge10);
        game.setChallenges(challenges);
        gameInformationRepository.save(game);
        challenge1.setGame(game);
        challenge2.setGame(game);
        challenge3.setGame(game);
        challenge4.setGame(game);
        challenge5.setGame(game);
        challenge6.setGame(game);
        challenge7.setGame(game);
        challenge8.setGame(game);
        challenge9.setGame(game);
        challenge10.setGame(game);
        challengeInformationRepository.save(challenge1);
        challengeInformationRepository.save(challenge2);
        challengeInformationRepository.save(challenge3);
        challengeInformationRepository.save(challenge4);
        challengeInformationRepository.save(challenge5);
        challengeInformationRepository.save(challenge6);
        challengeInformationRepository.save(challenge7);
        challengeInformationRepository.save(challenge8);
        challengeInformationRepository.save(challenge9);
        challengeInformationRepository.save(challenge10);

        List<Challenge> challengesMedium = new ArrayList<>();
        challengesMedium.add(challenge11);
        challengesMedium.add(challenge12);
        challengesMedium.add(challenge13);
        challengesMedium.add(challenge14);
        challengesMedium.add(challenge15);
        challengesMedium.add(challenge16);
        challengesMedium.add(challenge17);
        challengesMedium.add(challenge18);
        challengesMedium.add(challenge19);
        challengesMedium.add(challenge20);
        game2.setChallenges(challengesMedium);
        gameInformationRepository.save(game2);
        challenge11.setGame(game2);
        challenge12.setGame(game2);
        challenge13.setGame(game2);
        challenge14.setGame(game2);
        challenge15.setGame(game2);
        challenge16.setGame(game2);
        challenge17.setGame(game2);
        challenge18.setGame(game2);
        challenge19.setGame(game2);
        challenge20.setGame(game2);
        challengeInformationRepository.save(challenge11);
        challengeInformationRepository.save(challenge12);
        challengeInformationRepository.save(challenge13);
        challengeInformationRepository.save(challenge14);
        challengeInformationRepository.save(challenge15);
        challengeInformationRepository.save(challenge16);
        challengeInformationRepository.save(challenge17);
        challengeInformationRepository.save(challenge18);
        challengeInformationRepository.save(challenge19);
        challengeInformationRepository.save(challenge20);

        List<Challenge> challengesDifficult = new ArrayList<>();
        challengesDifficult.add(challenge21);
        challengesDifficult.add(challenge22);
        challengesDifficult.add(challenge23);
        challengesDifficult.add(challenge24);
        challengesDifficult.add(challenge25);
        challengesDifficult.add(challenge26);
        challengesDifficult.add(challenge27);
        challengesDifficult.add(challenge28);
        challengesDifficult.add(challenge29);
        challengesDifficult.add(challenge30);
        game3.setChallenges(challengesDifficult);
        gameInformationRepository.save(game3);
        challenge21.setGame(game3);
        challenge22.setGame(game3);
        challenge23.setGame(game3);
        challenge24.setGame(game3);
        challenge25.setGame(game3);
        challenge26.setGame(game3);
        challenge27.setGame(game3);
        challenge28.setGame(game3);
        challenge29.setGame(game3);
        challenge30.setGame(game3);
        challengeInformationRepository.save(challenge21);
        challengeInformationRepository.save(challenge22);
        challengeInformationRepository.save(challenge23);
        challengeInformationRepository.save(challenge24);
        challengeInformationRepository.save(challenge25);
        challengeInformationRepository.save(challenge26);
        challengeInformationRepository.save(challenge27);
        challengeInformationRepository.save(challenge28);
        challengeInformationRepository.save(challenge29);
        challengeInformationRepository.save(challenge30);



        User user = new User("naamnaam" ,"email@gmail.com", encoder.encode("Wachtwoord12!"));
        Set<Role> roles = new HashSet<>();
        Role userRole = roleRepository.findByName(ERole.ROLE_USER)
                .orElseThrow(() -> new RuntimeException("ROLE NOT FOUND"));
        roles.add(userRole);
        user.setRoles(roles);
        List<Challenge> privateToDo = new ArrayList<>();
        privateToDo.add(challenge1);
        privateToDo.add(challenge11);
        privateToDo.add(challenge21);
        user.setPrivateToDo(privateToDo);
        List<Challenge> publicToDo = new ArrayList<>();
        publicToDo.add(challenge4);
        publicToDo.add(challenge15);
        publicToDo.add(challenge26);
        user.setPublicToDo(publicToDo);
        List<Challenge> completedToDo = new ArrayList<>();
        completedToDo.add(challenge7);
        completedToDo.add(challenge18);
        completedToDo.add(challenge29);
        user.setCompletedToDo(completedToDo);
        userRepository.save(user);
    }
}